"""empty message

Revision ID: 642cad4bacf1
Revises: 67b4265c735f
Create Date: 2017-11-13 23:28:47.624607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '642cad4bacf1'
down_revision = '67b4265c735f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('about_me', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('location', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
